### ISSUE TITLE
the source code of the java version is a shit

### ISSUE THREAD

**Issue by helio-frota** [EsmerilProgramming/dinga_invaders#15]
so to avoid waste time, this must to be rewritten

**Comment by htmfilho** [comment]
If you are considering rewriting it, why don't you consider a pure Clojure approach like http://quil.info ? The API is quite comprehensive http://quil.info/api and I would contribute much more.

Dinga Invaders as it is today is all about Java-Clojure Interoperability, not functional Clojure. It forces you to keep thinking in terms of objects, when objects actually push you back from the functional world. Think about that.

**Comment by eprogramming** [comment]
@htmfilho 

>Dinga Invaders as it is today is all about Java-Clojure Interoperability, not functional Clojure. It forces you to keep thinking in terms of objects, when objects actually push you back from the functional world. Think about that.

yup, you're right.
i saw it, the java-swing api is fckng all, making all more difficult.

but the idea is not to add libs, just because nowadays lots of libs do almost everything for a small game, then I learn nothing, instead hack, and research now to make things done, I will turn into "super lib user".

**Comment by eprogramming** [comment]
the source is going here:
https://github.com/EsmerilProgramming/dinga_invaders/tree/master/dingainvaders
i'm running 'lein run' from this path

**Comment by htmfilho** [comment]
You would not add a lib, but replace another one - swing is a lib, right? So, quil would replace it. In the Clojure World, the language core is very light and libraries are the way to go, adding just the necessary. Therefore, Clojure already does what Java folks are trying to do in Java 9 (a.k.a. project jigsaw): modularity.

Btw, it's better to learn community stuff (quil) than Oracle stuff (Swing) ;-)

**Comment by eprogramming** [comment]
we can use this:
https://github.com/daveray/seesaw
> "Seesaw turns the Horror of Swing into a friendly"

http://darevay.com/talks/clojurewest2012/#/title-slide

to replace java-swing because this lib is not specific to a game

**Comment by htmfilho** [comment]
Well, now, instead of one, you have two libs :P But that's ok. At least it's idiomatic Clojure :-)

**Comment by eprogramming** [comment]
we can use quil on 2.0 version with no problem... but i guess i will lost the opportunity of learn more clojure... now i trying to participate of  2 projects to help to learn clojure: this and dev-utility-belt

**Comment by eprogramming** [comment]
but i guess i will lost the opportunity of learn more clojure... if we use this now..

**Comment by htmfilho** [comment]
Why do you think Quil is preventing you from learning Clojure? It is a idiomatic Clojure library. Btw, did you tried something in dev-utility-belt ?

**Comment by eprogramming** [comment]
> Btw, did you tried something in dev-utility-belt ?

still trying to understand : ]

**Comment by htmfilho** [comment]
Ask questions!!!!

**Comment by eprogramming** [comment]
I will try to do an issue, then start to ask questions if needed ofc.
thanks !

**Comment by eprogramming** [comment]
Ok , i'm going to try to [quil](http://quil.info/) it

**Comment by eprogramming** [comment]
: /
**13M** Aug  3 11:34 quil_with_power-0.1.0-SNAPSHOT-standalone.jar
not good after create the uber jar 13mb final jar o_0
looking for others solutions..

**Comment by eprogramming** [comment]
The problem is not clojure... the problem is Java Swing.
Maybe going to migrate this game to Go lang.
And use this https://github.com/google/gxui
